-- 코드를 작성해주세요.
SELECT ID, fn.FISH_NAME, fi.LENGTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH,
           ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS rn
    FROM FISH_INFO
) fi
JOIN FISH_NAME_INFO fn
  ON fi.FISH_TYPE = fn.FISH_TYPE
WHERE fi.rn = 1
ORDER BY fi.ID;
